version: '3'

services:
  mygrafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  myprometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
      # - "9100:9100"
    volumes:
      - ./prometheus:/etc/prometheus
    # network_mode: host
